export const cats = [
  "https://crva.imgix.net/hero-images/cats-and-craft-beer.jpg?auto=compress%2Cformat&fit=crop&fm=webp&ixlib=php-3.1.0&q=80&v=1554820621",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT63JFzUmrwqpZThXbIh-QWoVczKNkxWZpeRYL_aVGftcnzvKahe4O277-8B429DJ-XWc4&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv6kbonDqLt81YkWivY0C7siyAGlLa5SlF38Bye5_J1yXdhTw9BAKKtuo-vL0fTLCXkeI&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4IT50de5FHuTVEws_D-lhbj4EjS5BgZodR0tomke3JzqYamOSPiwQYs2n3-qTKJlt95s&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG-g12hjCAxWbpKFFVXI3sSx9RBGUNOj0CeCsa4782RH13_TRZK4nL33infECc9nD42vc&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7mWGrmhT_UD-qUTO5LxmC1BwoWs4r-zlx6ICMXX2kJysv7Pz85isBpuyRVP-L8bU3Mh4&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbDHxL-5_hz4KGRuvsXSFHGGQqi0CsDEPV4mhof_fQtu6U923WDnxDpykMT3ptOMndT-A&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSP3DGCbIUIYDQcS6SckMIRW-droFLz2dnLTNkeUt4gUWLBZmG36FTf4UoW6bDQxNeyrTM&usqp=CAU",
  "https://vinepair.com/wp-content/uploads/2017/05/rosie-card.jpg",
  "https://portland.thedrinknation.com/uploads/images/beercats/beer-cat-1.jpg",
  "https://portland.thedrinknation.com/uploads/images/beercats/beer-cat-2.jpg",
  "https://portland.thedrinknation.com/uploads/images/beercats/beer-cat-5.jpg",
  "https://portland.thedrinknation.com/uploads/images/beercats/beer-cat-9.jpg",
  "https://portland.thedrinknation.com/uploads/images/beercats/beer-cat-11.jpg",
  "https://portland.thedrinknation.com/uploads/images/beercats/beer-cat-8.jpg",
  "https://portland.thedrinknation.com/uploads/Riley_cat_drinking.JPG",
];
