export const cats = [
  require("./assets/BeerCats/1.jpg"),
  require("./assets/BeerCats/2.jpg"),
  require("./assets/BeerCats/3.jpg"),
  require("./assets/BeerCats/4.jpg"),
  require("./assets/BeerCats/5.jpg"),
  require("./assets/BeerCats/6.jpg"),
  require("./assets/BeerCats/7.jpg"),
  require("./assets/BeerCats/8.jpg"),
  require("./assets/BeerCats/9.jpg"),
  require("./assets/BeerCats/10.jpg"),
  require("./assets/BeerCats/11.jpg"),
  require("./assets/BeerCats/12.jpg"),
  require("./assets/BeerCats/13.jpg"),
];
